[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GHita", email = "ghita.sefraoui77@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.141.1",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
